version: "3"

services:
  cypress:
    build: .
    volumes:
      - ./out:/app/out
      - ./cypress/reports:/app/cypress/reports
      - ./cypress/screenshots:/app/cypress/screenshots
      - ./cypress/snapshots:/app/cypress/snapshots
      